#define _GNU_SOURCE
#include "wmswitch/generator.h"
#include "wmswitch/logging.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>

static void write_hyprland_header(FILE *fp) {
    time_t now = time(NULL);
    struct tm *local = localtime(&now);
    
    fprintf(fp, "# Hyprland configuration\n");
    fprintf(fp, "# Generated by wmswitch on %04d-%02d-%02d %02d:%02d:%02d\n",
            local->tm_year + 1900, local->tm_mon + 1, local->tm_mday,
            local->tm_hour, local->tm_min, local->tm_sec);
    fprintf(fp, "# See https://wiki.hyprland.org/Configuring/Configuring-Hyprland/ for more\n\n");
}

static void write_hyprland_defaults(FILE *fp) {
    fprintf(fp, "# Default configuration\n");
    fprintf(fp, "$mainMod = SUPER\n\n");
    
    fprintf(fp, "# Monitor configuration\n");
    fprintf(fp, "monitor=,preferred,auto,auto\n\n");
    
    fprintf(fp, "# Input configuration\n");
    fprintf(fp, "input {\n");
    fprintf(fp, "    kb_layout = us\n");
    fprintf(fp, "    kb_variant =\n");
    fprintf(fp, "    kb_model =\n");
    fprintf(fp, "    kb_options =\n");
    fprintf(fp, "    kb_rules =\n");
    fprintf(fp, "    follow_mouse = 1\n");
    fprintf(fp, "    touchpad {\n");
    fprintf(fp, "        natural_scroll = no\n");
    fprintf(fp, "    }\n");
    fprintf(fp, "    sensitivity = 0\n");
    fprintf(fp, "}\n\n");
    
    fprintf(fp, "# General configuration\n");
    fprintf(fp, "general {\n");
    fprintf(fp, "    gaps_in = 5\n");
    fprintf(fp, "    gaps_out = 20\n");
    fprintf(fp, "    border_size = 2\n");
    fprintf(fp, "    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg\n");
    fprintf(fp, "    col.inactive_border = rgba(595959aa)\n");
    fprintf(fp, "    layout = dwindle\n");
    fprintf(fp, "}\n\n");
    
    fprintf(fp, "# Decoration\n");
    fprintf(fp, "decoration {\n");
    fprintf(fp, "    rounding = 10\n");
    fprintf(fp, "    blur {\n");
    fprintf(fp, "        enabled = true\n");
    fprintf(fp, "        size = 3\n");
    fprintf(fp, "        passes = 1\n");
    fprintf(fp, "    }\n");
    fprintf(fp, "    drop_shadow = yes\n");
    fprintf(fp, "    shadow_range = 4\n");
    fprintf(fp, "    shadow_render_power = 3\n");
    fprintf(fp, "    col.shadow = rgba(1a1a1aee)\n");
    fprintf(fp, "}\n\n");
    
    fprintf(fp, "# Animations\n");
    fprintf(fp, "animations {\n");
    fprintf(fp, "    enabled = yes\n");
    fprintf(fp, "    bezier = myBezier, 0.05, 0.9, 0.1, 1.05\n");
    fprintf(fp, "    animation = windows, 1, 7, myBezier\n");
    fprintf(fp, "    animation = windowsOut, 1, 7, default, popin 80%%\n");
    fprintf(fp, "    animation = border, 1, 10, default\n");
    fprintf(fp, "    animation = borderangle, 1, 8, default\n");
    fprintf(fp, "    animation = fade, 1, 7, default\n");
    fprintf(fp, "    animation = workspaces, 1, 6, default\n");
    fprintf(fp, "}\n\n");
    
    fprintf(fp, "# Layouts\n");
    fprintf(fp, "dwindle {\n");
    fprintf(fp, "    pseudotile = yes\n");
    fprintf(fp, "    preserve_split = yes\n");
    fprintf(fp, "}\n\n");
    
    fprintf(fp, "master {\n");
    fprintf(fp, "    new_is_master = true\n");
    fprintf(fp, "}\n\n");
    
    fprintf(fp, "# Gestures\n");
    fprintf(fp, "gestures {\n");
    fprintf(fp, "    workspace_swipe = off\n");
    fprintf(fp, "}\n\n");
}

static void write_hyprland_workspaces(FILE *fp, wmswitch_parsed_config_t *config) {
    if (config->workspace_count == 0) {
        return;
    }
    
    fprintf(fp, "# Workspace configuration\n");
    
    for (int i = 0; i < config->workspace_count; i++) {
        wmswitch_workspace_t *ws = &config->workspaces[i];
        
        if (ws->monitor && strlen(ws->monitor) > 0) {
            if (ws->number > 0) {
                fprintf(fp, "workspace = %d, monitor:%s\n", ws->number, ws->monitor);
            } else {
                fprintf(fp, "workspace = name:%s, monitor:%s\n", ws->name, ws->monitor);
            }
        }
        
        if (ws->number > 0) {
            fprintf(fp, "# Workspace %s is number %d\n", ws->name, ws->number);
        }
    }
    fprintf(fp, "\n");
}

static char* convert_keybind_to_hyprland(const char *keybind) {
    if (!keybind) return NULL;
    
    size_t len = strlen(keybind);
    char *result = malloc(len * 2 + 1);
    if (!result) return NULL;
    
    strcpy(result, keybind);
    
    // Replace mod+ with $mainMod + (space-separated)
    char *pos = strstr(result, "mod+");
    while (pos) {
        memmove(pos + 9, pos + 4, strlen(pos + 4) + 1);
        memcpy(pos, "$mainMod ", 9);
        pos = strstr(pos + 9, "mod+");
    }
    
    // Replace shift+ with SHIFT + (space-separated, uppercase)
    pos = strstr(result, "shift+");
    while (pos) {
        memmove(pos + 6, pos + 6, strlen(pos + 6) + 1);
        memcpy(pos, "SHIFT ", 6);
        pos = strstr(pos + 6, "shift+");
    }
    
    // Replace ctrl+ with CTRL +
    pos = strstr(result, "ctrl+");
    while (pos) {
        memmove(pos + 5, pos + 5, strlen(pos + 5) + 1);
        memcpy(pos, "CTRL ", 5);
        pos = strstr(pos + 5, "ctrl+");
    }
    
    // Replace alt+ with ALT +
    pos = strstr(result, "alt+");
    while (pos) {
        memmove(pos + 4, pos + 4, strlen(pos + 4) + 1);
        memcpy(pos, "ALT ", 4);
        pos = strstr(pos + 4, "alt+");
    }
    
    // Convert remaining keys to uppercase for consistency
    for (char *c = result; *c; c++) {
        if (*c >= 'a' && *c <= 'z' && 
            (c == result || *(c-1) == ' ') && 
            (*(c+1) == '\0' || *(c+1) == ' ')) {
            *c = *c - 'a' + 'A';
        }
    }
    
    return result;
}

static char* convert_command_to_hyprland(const char *command) {
    if (!command) return NULL;
    
    if (strncmp(command, "workspace ", 10) == 0) {
        const char *ws_name = command + 10;
        char *result = malloc(strlen(ws_name) + 20);
        sprintf(result, "workspace, %s", ws_name);
        return result;
    }
    
    if (strncmp(command, "move container to workspace ", 28) == 0) {
        const char *ws_name = command + 28;
        char *result = malloc(strlen(ws_name) + 30);
        sprintf(result, "movetoworkspace, %s", ws_name);
        return result;
    }
    
    if (strncmp(command, "exec ", 5) == 0) {
        const char *exec_cmd = command + 5;
        char *result = malloc(strlen(exec_cmd) + 10);
        sprintf(result, "exec, %s", exec_cmd);
        return result;
    }
    
    // Default: assume it's a dispatcher command
    char *result = malloc(strlen(command) + 10);
    sprintf(result, "exec, %s", command);
    return result;
}

static void write_hyprland_keybinds(FILE *fp, wmswitch_parsed_config_t *config) {
    if (config->keybind_count == 0) {
        return;
    }
    
    fprintf(fp, "# Key bindings\n");
    
    for (int i = 0; i < config->keybind_count; i++) {
        wmswitch_keybind_t *kb = &config->keybinds[i];
        
        if (kb->wm_exclusive && strcmp(kb->wm_exclusive, "hyprland") != 0) {
            fprintf(fp, "# Skipping keybind exclusive to %s: %s\n", kb->wm_exclusive, kb->key_combo);
            continue;
        }
        
        char *hypr_key = convert_keybind_to_hyprland(kb->key_combo);
        char *hypr_cmd = convert_command_to_hyprland(kb->command);
        
        if (hypr_key && hypr_cmd) {
            fprintf(fp, "bind = %s, %s\n", hypr_key, hypr_cmd);
        }
        
        free(hypr_key);
        free(hypr_cmd);
    }
    fprintf(fp, "\n");
}

static void write_hyprland_default_keybinds(FILE *fp) {
    fprintf(fp, "# Default Hyprland keybindings\n");
    fprintf(fp, "bind = $mainMod, Q, killactive,\n");
    fprintf(fp, "bind = $mainMod, M, exit,\n");
    fprintf(fp, "bind = $mainMod, E, exec, dolphin\n");
    fprintf(fp, "bind = $mainMod, V, togglefloating,\n");
    fprintf(fp, "bind = $mainMod, R, exec, wofi --show drun\n");
    fprintf(fp, "bind = $mainMod, P, pseudo, # dwindle\n");
    fprintf(fp, "bind = $mainMod, J, togglesplit, # dwindle\n");
    fprintf(fp, "\n");
    
    fprintf(fp, "# Move focus with mainMod + arrow keys\n");
    fprintf(fp, "bind = $mainMod, left, movefocus, l\n");
    fprintf(fp, "bind = $mainMod, right, movefocus, r\n");
    fprintf(fp, "bind = $mainMod, up, movefocus, u\n");
    fprintf(fp, "bind = $mainMod, down, movefocus, d\n");
    fprintf(fp, "\n");
    
    fprintf(fp, "# Switch workspaces with mainMod + [0-9]\n");
    for (int i = 1; i <= 10; i++) {
        int key = (i == 10) ? 0 : i;
        fprintf(fp, "bind = $mainMod, %d, workspace, %d\n", key, i);
    }
    fprintf(fp, "\n");
    
    fprintf(fp, "# Move active window to a workspace with mainMod + SHIFT + [0-9]\n");
    for (int i = 1; i <= 10; i++) {
        int key = (i == 10) ? 0 : i;
        fprintf(fp, "bind = $mainMod SHIFT, %d, movetoworkspace, %d\n", key, i);
    }
    fprintf(fp, "\n");
    
    fprintf(fp, "# Scroll through existing workspaces with mainMod + scroll\n");
    fprintf(fp, "bind = $mainMod, mouse_down, workspace, e+1\n");
    fprintf(fp, "bind = $mainMod, mouse_up, workspace, e-1\n");
    fprintf(fp, "\n");
    
    fprintf(fp, "# Move/resize windows with mainMod + LMB/RMB and dragging\n");
    fprintf(fp, "bindm = $mainMod, mouse:272, movewindow\n");
    fprintf(fp, "bindm = $mainMod, mouse:273, resizewindow\n");
    fprintf(fp, "\n");
}

int wmswitch_hyprland_generate(wmswitch_parsed_config_t *config, const char *output_path, int dry_run) {
    if (!config || !output_path) {
        wmswitch_log_error("Invalid parameters for Hyprland config generation");
        return 0;
    }
    
    if (dry_run) {
        wmswitch_log_info("DRY RUN: Would generate Hyprland config at: %s", output_path);
        wmswitch_log_info("  - %d workspaces would be configured", config->workspace_count);
        wmswitch_log_info("  - %d keybinds would be added", config->keybind_count);
        return 1;
    }
    
    FILE *fp = fopen(output_path, "w");
    if (!fp) {
        wmswitch_log_error("Failed to open Hyprland config file for writing: %s", output_path);
        return 0;
    }
    
    write_hyprland_header(fp);
    write_hyprland_defaults(fp);
    write_hyprland_workspaces(fp, config);
    write_hyprland_keybinds(fp, config);
    write_hyprland_default_keybinds(fp);
    
    fclose(fp);
    
    wmswitch_log_info("Successfully generated Hyprland config: %s", output_path);
    return 1;
}

int wmswitch_validate_hyprland_config(const char *config_path) {
    wmswitch_log_debug("Validating Hyprland config: %s", config_path);
    
    if (access(config_path, R_OK) != 0) {
        wmswitch_log_error("Cannot read Hyprland config file: %s", config_path);
        return 0;
    }
    
    // Hyprland doesn't have a built-in config validator like i3
    // We'll do basic syntax checking
    FILE *fp = fopen(config_path, "r");
    if (!fp) {
        wmswitch_log_error("Failed to open Hyprland config for validation: %s", config_path);
        return 0;
    }
    
    char line[1024];
    int line_num = 0;
    int valid = 1;
    
    while (fgets(line, sizeof(line), fp)) {
        line_num++;
        // Basic syntax validation - check for malformed bind statements
        if (strncmp(line, "bind", 4) == 0 && strchr(line, '=') == NULL) {
            wmswitch_log_warning("Line %d: Malformed bind statement: %s", line_num, line);
            valid = 0;
        }
    }
    
    fclose(fp);
    
    if (valid) {
        wmswitch_log_debug("Hyprland config validation passed");
    } else {
        wmswitch_log_warning("Hyprland config validation found issues");
    }
    
    return valid;
}