#define _GNU_SOURCE
#include "wmswitch/generator.h"
#include "wmswitch/logging.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>
#include <limits.h>

static void write_i3_header(FILE *fp) {
    time_t now = time(NULL);
    struct tm *local = localtime(&now);
    
    fprintf(fp, "# i3 config file (v4)\n");
    fprintf(fp, "# Generated by wmswitch on %04d-%02d-%02d %02d:%02d:%02d\n",
            local->tm_year + 1900, local->tm_mon + 1, local->tm_mday,
            local->tm_hour, local->tm_min, local->tm_sec);
    fprintf(fp, "# Please see https://i3wm.org/docs/userguide.html for a complete reference!\n\n");
}

static void write_i3_defaults(FILE *fp) {
    fprintf(fp, "# Set mod key (Mod1=Alt, Mod4=Super/Windows)\n");
    fprintf(fp, "set $mod Mod4\n\n");
    
    fprintf(fp, "# Font for window titles\n");
    fprintf(fp, "font pango:DejaVu Sans Mono 8\n\n");
    
    fprintf(fp, "# Use Mouse+$mod to drag floating windows\n");
    fprintf(fp, "floating_modifier $mod\n\n");
    
    fprintf(fp, "# Start i3bar to display a workspace bar\n");
    fprintf(fp, "bar {\n");
    fprintf(fp, "    status_command i3status\n");
    fprintf(fp, "}\n\n");
}

static void write_i3_workspaces(FILE *fp, wmswitch_parsed_config_t *config) {
    if (config->workspace_count == 0) {
        return;
    }
    
    fprintf(fp, "# Workspace configuration\n");
    
    for (int i = 0; i < config->workspace_count; i++) {
        wmswitch_workspace_t *ws = &config->workspaces[i];
        
        if (ws->monitor && strlen(ws->monitor) > 0) {
            fprintf(fp, "workspace \"%s\" output %s\n", ws->name, ws->monitor);
        }
        
        if (ws->number > 0) {
            fprintf(fp, "# Workspace %s is number %d\n", ws->name, ws->number);
        }
    }
    fprintf(fp, "\n");
}

static char* convert_keybind_to_i3(const char *keybind) {
    if (!keybind) return NULL;
    
    size_t len = strlen(keybind);
    char *result = malloc(len * 2 + 1); // Extra space for longer replacements
    if (!result) return NULL;
    
    strcpy(result, keybind);
    
    // Replace mod+ with $mod+
    char *pos = strstr(result, "mod+");
    while (pos) {
        memmove(pos + 5, pos + 4, strlen(pos + 4) + 1);
        memcpy(pos, "$mod+", 5);
        pos = strstr(pos + 5, "mod+");
    }
    
    // Replace shift+ with Shift+
    pos = strstr(result, "shift+");
    while (pos) {
        pos[0] = 'S'; // shift -> Shift
        pos = strstr(pos + 6, "shift+");
    }
    
    // Replace ctrl+ with Ctrl+
    pos = strstr(result, "ctrl+");
    while (pos) {
        pos[0] = 'C'; // ctrl -> Ctrl
        pos = strstr(pos + 5, "ctrl+");
    }
    
    // Replace alt+ with Mod1+
    pos = strstr(result, "alt+");
    while (pos) {
        memmove(pos + 5, pos + 4, strlen(pos + 4) + 1);
        memcpy(pos, "Mod1+", 5);
        pos = strstr(pos + 5, "alt+");
    }
    
    return result;
}

static char* convert_command_to_i3(const char *command) {
    if (!command) return NULL;
    
    if (strncmp(command, "workspace ", 10) == 0) {
        const char *ws_name = command + 10;
        char *result = malloc(strlen(ws_name) + 20);
        sprintf(result, "workspace \"%s\"", ws_name);
        return result;
    }
    
    if (strncmp(command, "move container to workspace ", 28) == 0) {
        const char *ws_name = command + 28;
        char *result = malloc(strlen(ws_name) + 35);
        sprintf(result, "move container to workspace \"%s\"", ws_name);
        return result;
    }
    
    if (strncmp(command, "exec ", 5) == 0) {
        return strdup(command);
    }
    
    return strdup(command);
}

static void write_i3_keybinds(FILE *fp, wmswitch_parsed_config_t *config) {
    if (config->keybind_count == 0) {
        return;
    }
    
    fprintf(fp, "# Key bindings\n");
    
    for (int i = 0; i < config->keybind_count; i++) {
        wmswitch_keybind_t *kb = &config->keybinds[i];
        
        if (kb->wm_exclusive && strcmp(kb->wm_exclusive, "i3") != 0) {
            fprintf(fp, "# Skipping keybind exclusive to %s: %s\n", kb->wm_exclusive, kb->key_combo);
            continue;
        }
        
        char *i3_key = convert_keybind_to_i3(kb->key_combo);
        char *i3_cmd = convert_command_to_i3(kb->command);
        
        if (i3_key && i3_cmd) {
            fprintf(fp, "bindsym %s %s\n", i3_key, i3_cmd);
        }
        
        free(i3_key);
        free(i3_cmd);
    }
    fprintf(fp, "\n");
}

static void write_i3_default_keybinds(FILE *fp) {
    fprintf(fp, "# Default i3 keybindings\n");
    fprintf(fp, "bindsym $mod+Shift+q kill\n");
    fprintf(fp, "bindsym $mod+Shift+c reload\n");
    fprintf(fp, "bindsym $mod+Shift+r restart\n");
    fprintf(fp, "bindsym $mod+Shift+e exec \"i3-nagbar -t warning -m 'Exit i3?' -b 'Yes' 'i3-msg exit'\"\n");
    fprintf(fp, "\n");
    
    fprintf(fp, "# Change focus\n");
    fprintf(fp, "bindsym $mod+j focus left\n");
    fprintf(fp, "bindsym $mod+k focus down\n");
    fprintf(fp, "bindsym $mod+l focus up\n");
    fprintf(fp, "bindsym $mod+semicolon focus right\n");
    fprintf(fp, "\n");
    
    fprintf(fp, "# Move focused window\n");
    fprintf(fp, "bindsym $mod+Shift+j move left\n");
    fprintf(fp, "bindsym $mod+Shift+k move down\n");
    fprintf(fp, "bindsym $mod+Shift+l move up\n");
    fprintf(fp, "bindsym $mod+Shift+semicolon move right\n");
    fprintf(fp, "\n");
    
    fprintf(fp, "# Split and layout\n");
    fprintf(fp, "bindsym $mod+h split h\n");
    fprintf(fp, "bindsym $mod+v split v\n");
    fprintf(fp, "bindsym $mod+f fullscreen toggle\n");
    fprintf(fp, "bindsym $mod+space floating toggle\n");
    fprintf(fp, "\n");
}

int wmswitch_i3_generate(wmswitch_parsed_config_t *config, const char *output_path, int dry_run) {
    if (!config || !output_path) {
        wmswitch_log_error("Invalid parameters for i3 config generation");
        return 0;
    }
    
    if (dry_run) {
        wmswitch_log_info("DRY RUN: Would generate i3 config at: %s", output_path);
        wmswitch_log_info("  - %d workspaces would be configured", config->workspace_count);
        wmswitch_log_info("  - %d keybinds would be added", config->keybind_count);
        return 1;
    }
    
    FILE *fp = fopen(output_path, "w");
    if (!fp) {
        wmswitch_log_error("Failed to open i3 config file for writing: %s", output_path);
        return 0;
    }
    
    write_i3_header(fp);
    write_i3_defaults(fp);
    write_i3_workspaces(fp, config);
    write_i3_keybinds(fp, config);
    write_i3_default_keybinds(fp);
    
    fclose(fp);
    
    wmswitch_log_info("Successfully generated i3 config: %s", output_path);
    return 1;
}

int wmswitch_validate_i3_config(const char *config_path) {
    wmswitch_log_debug("Validating i3 config: %s", config_path);
    
    if (access(config_path, R_OK) != 0) {
        wmswitch_log_error("Cannot read i3 config file: %s", config_path);
        return 0;
    }
    
    char cmd[PATH_MAX + 20];
    snprintf(cmd, sizeof(cmd), "i3 -C -c \"%s\"", config_path);
    
    int result = system(cmd);
    if (result == 0) {
        wmswitch_log_debug("i3 config validation passed");
        return 1;
    } else {
        wmswitch_log_warning("i3 config validation failed (exit code: %d)", result);
        return 0;
    }
}