#define _GNU_SOURCE
#include "wmswitch/wizard.h"
#include "wmswitch/logging.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

static char* read_input(const char *prompt, const char *default_value) {
    printf("%s", prompt);
    if (default_value) {
        printf(" [%s]", default_value);
    }
    printf(": ");
    fflush(stdout);
    
    char *line = NULL;
    size_t len = 0;
    ssize_t read = getline(&line, &len, stdin);
    
    if (read == -1) {
        return NULL;
    }
    
    // Remove trailing newline
    if (line[read - 1] == '\n') {
        line[read - 1] = '\0';
    }
    
    // Use default if empty
    if (strlen(line) == 0 && default_value) {
        free(line);
        return strdup(default_value);
    }
    
    return line;
}

static int read_yes_no(const char *prompt, int default_yes) {
    char *response = read_input(prompt, default_yes ? "Y/n" : "y/N");
    if (!response) return default_yes;
    
    int result = default_yes;
    if (strlen(response) > 0) {
        char first = response[0];
        if (first == 'y' || first == 'Y') {
            result = 1;
        } else if (first == 'n' || first == 'N') {
            result = 0;
        }
    }
    
    free(response);
    return result;
}

static void print_welcome(void) {
    printf("\n");
    printf("╭─────────────────────────────────────╮\n");
    printf("│        wmswitch Setup Wizard        │\n");
    printf("╰─────────────────────────────────────╯\n\n");
    printf("This wizard will help you create a wmswitch configuration\n");
    printf("for i3, Hyprland, and AeroSpace window managers.\n\n");
    printf("Press Ctrl+C at any time to cancel.\n\n");
}

static wmswitch_wizard_config_t* collect_config(void) {
    wmswitch_wizard_config_t *config = calloc(1, sizeof(wmswitch_wizard_config_t));
    if (!config) return NULL;
    
    printf("🔧 Application Configuration\n");
    printf("─────────────────────────\n");
    
    config->terminal = read_input("Terminal emulator", "alacritty");
    config->app_launcher = read_input("Application launcher", "rofi -show drun");
    config->file_manager = read_input("File manager", "nautilus");
    config->browser = read_input("Web browser", "firefox");
    
    printf("\n🖥️  Monitor Configuration\n");
    printf("────────────────────────\n");
    
    config->primary_monitor = read_input("Primary monitor name", "main");
    if (read_yes_no("Do you have a secondary monitor?", 0)) {
        config->secondary_monitor = read_input("Secondary monitor name", "secondary");
    }
    
    printf("\n🏠 Workspace Configuration\n");
    printf("─────────────────────────\n");
    
    char *ws_count_str = read_input("Number of workspaces (1-10)", "4");
    config->workspace_count = atoi(ws_count_str);
    if (config->workspace_count < 1) config->workspace_count = 1;
    if (config->workspace_count > 10) config->workspace_count = 10;
    free(ws_count_str);
    
    config->workspace_names = calloc(config->workspace_count, sizeof(char*));
    
    const char *default_names[] = {"dev", "web", "comm", "media", "music", 
                                  "games", "docs", "tmp", "sys", "extra"};
    
    for (int i = 0; i < config->workspace_count; i++) {
        char prompt[100];
        snprintf(prompt, sizeof(prompt), "Workspace %d name", i + 1);
        config->workspace_names[i] = read_input(prompt, default_names[i]);
    }
    
    printf("\n⌨️  Keybinding Preferences\n");
    printf("─────────────────────────\n");
    
    config->use_vim_bindings = read_yes_no("Use vim-style movement keys (hjkl)?", 1);
    config->enable_floating = read_yes_no("Enable floating window support?", 1);
    
    return config;
}

static void write_toml_config(const char *output_path, wmswitch_wizard_config_t *config) {
    FILE *fp = fopen(output_path, "w");
    if (!fp) {
        wmswitch_log_error("Failed to create config file: %s", output_path);
        return;
    }
    
    fprintf(fp, "# wmswitch configuration\n");
    fprintf(fp, "# Generated by wmswitch wizard\n\n");
    
    // Write workspaces
    for (int i = 0; i < config->workspace_count; i++) {
        fprintf(fp, "[workspaces.%s]\n", config->workspace_names[i]);
        fprintf(fp, "number = %d\n", i + 1);
        
        if (config->secondary_monitor && i >= config->workspace_count / 2) {
            fprintf(fp, "monitor = \"%s\"\n", config->secondary_monitor);
        } else {
            fprintf(fp, "monitor = \"%s\"\n", config->primary_monitor);
        }
        fprintf(fp, "\n");
    }
    
    // Write keybinds
    fprintf(fp, "[keybinds]\n");
    
    // Workspace switching
    for (int i = 0; i < config->workspace_count; i++) {
        fprintf(fp, "\"mod+%d\" = \"workspace %d\"\n", i + 1, i + 1);
        fprintf(fp, "\"mod+shift+%d\" = \"move container to workspace %d\"\n", i + 1, i + 1);
    }
    
    // Application keybinds
    fprintf(fp, "\"mod+return\" = \"exec %s\"\n", config->terminal);
    fprintf(fp, "\"mod+d\" = \"exec %s\"\n", config->app_launcher);
    fprintf(fp, "\"mod+e\" = \"exec %s\"\n", config->file_manager);
    fprintf(fp, "\"mod+w\" = \"exec %s\"\n", config->browser);
    
    // Window management
    if (config->use_vim_bindings) {
        fprintf(fp, "\"mod+h\" = \"focus left\"\n");
        fprintf(fp, "\"mod+j\" = \"focus down\"\n");
        fprintf(fp, "\"mod+k\" = \"focus up\"\n");
        fprintf(fp, "\"mod+l\" = \"focus right\"\n");
        fprintf(fp, "\"mod+shift+h\" = \"move left\"\n");
        fprintf(fp, "\"mod+shift+j\" = \"move down\"\n");
        fprintf(fp, "\"mod+shift+k\" = \"move up\"\n");
        fprintf(fp, "\"mod+shift+l\" = \"move right\"\n");
    }
    
    if (config->enable_floating) {
        fprintf(fp, "\"mod+shift+space\" = \"toggle floating\"\n");
    }
    
    fprintf(fp, "\"mod+shift+q\" = \"kill window\"\n");
    fprintf(fp, "\"mod+f\" = \"fullscreen toggle\"\n");
    
    fclose(fp);
}

int wmswitch_run_wizard(const char *output_path) {
    print_welcome();
    
    wmswitch_wizard_config_t *config = collect_config();
    if (!config) {
        wmswitch_log_error("Failed to collect configuration");
        return 0;
    }
    
    printf("\n📝 Configuration Summary\n");
    printf("────────────────────────\n");
    printf("Terminal: %s\n", config->terminal);
    printf("Launcher: %s\n", config->app_launcher);
    printf("Workspaces: %d (", config->workspace_count);
    for (int i = 0; i < config->workspace_count; i++) {
        printf("%s", config->workspace_names[i]);
        if (i < config->workspace_count - 1) printf(", ");
    }
    printf(")\n");
    printf("Primary monitor: %s\n", config->primary_monitor);
    if (config->secondary_monitor) {
        printf("Secondary monitor: %s\n", config->secondary_monitor);
    }
    printf("Vim bindings: %s\n", config->use_vim_bindings ? "Yes" : "No");
    printf("Floating support: %s\n", config->enable_floating ? "Yes" : "No");
    
    if (!read_yes_no("\nSave this configuration?", 1)) {
        printf("Configuration cancelled.\n");
        wmswitch_wizard_config_free(config);
        return 0;
    }
    
    write_toml_config(output_path, config);
    printf("\n✅ Configuration saved to: %s\n", output_path);
    printf("\nNext steps:\n");
    printf("1. Review and edit the config file if needed\n");
    printf("2. Run: wmswitch generate %s\n", output_path);
    printf("3. Restart your window manager\n\n");
    
    wmswitch_wizard_config_free(config);
    return 1;
}

void wmswitch_wizard_config_free(wmswitch_wizard_config_t *config) {
    if (!config) return;
    
    free(config->terminal);
    free(config->app_launcher);
    free(config->file_manager);
    free(config->browser);
    free(config->primary_monitor);
    free(config->secondary_monitor);
    
    for (int i = 0; i < config->workspace_count; i++) {
        free(config->workspace_names[i]);
    }
    free(config->workspace_names);
    
    free(config);
}